# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "slave_1" do |slave_1|

    slave_1.vm.hostname = "slave-1"
    slave_1.vm.box = "ubuntu/jammy64"
    slave_1.vm.network "private_network", ip: "192.168.33.10"
    slave_1.vm.boot_timeout = 600
    
  end

  config.vm.define "master" do |master|

    master.vm.hostname = "master"
    master.vm.box = "ubuntu/jammy64"
    master.vm.network "private_network", ip: "192.168.33.11"
    master.vm.boot_timeout = 600 
    master.vm.provision "shell", path: "lamp.sh"
    # master.vm.provision "shell", path: "config_webserver.sh"
  end

    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "2"
    end
end
